Repository ssafy-yummy/algorithm-marathon, pull requests merged in 2022-10, with the labels that each got.

#89 WONJOON : BOJ 16234 G5 인구 이동
  wonjoon/src/week10/BOJ_20207_S1_달력.java
  wonjoon/src/week9/BOJ_16234_G5_인구이동.java
  wonjoon/src/week9/BOJ_1916_G5_최소비용구하기.java
  wonjoon/src/week9/BOJ_1976_G4_여행가자_DFS.java
  wonjoon/src/week9/BOJ_1976_G4_여행가자_UF.java
  wonjoon/src/week9/BOJ_2252_G3_줄세우기.java
Labels: Simulation, BFS

#99 WONJOON : BOJ 21608 G5 상어 초등학교
  wonjoon/src/week10/BOJ_1309_S1_동물원.java
  wonjoon/src/week10/BOJ_20207_S1_달력.java
  wonjoon/src/week10/BOJ_21608_G5_상어초등학교.java
  wonjoon/src/week10/BOJ_2225_G5_합분해.java
Labels: Simulation, PriorityQueue

#100 MYEONGGYU : BOJ 1309 S1 동물원
  myeonggyu/src/week10/BOJ_1309_S1_동물원.java
  myeonggyu/src/week10/BOJ_20207_S1_달력.java
  myeonggyu/src/week10/BOJ_21608_G5_상어초등학교.java
  myeonggyu/src/week10/BOJ_2225_G5_합분해.java
Labels: DP
